AllCops:
  TargetRubyVersion: 2.5

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Metrics/LineLength:
  Max: 85

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/HashSyntax:
  EnforcedStyle: hash_rockets
